# 演示Go语言读取TOML配置文件的示例

# 1. 字符串
host = "192.168.0.103"

# 2. 整数
strength = 90

# 3. 浮点数
pi = 3.1415926

# 4. 布尔值
is_true = true

# 5. 本地日期时刻
ldt = 2024-01-07T07:32:00
ld1 = 2024-01-07 # 注意：在本地日期类型后面一定要有空格，否则文件读取会失败
lt1 = 00:32:00

# 6. 数组
arr1 = [0, 1, 2]
arr2 = ["a", "b", "c"]

# 8. 内联表
# 注意：本示例中内联表要放在表的前面来定义，否则会被当成表的一部分
server1 = {address = "192.168.0.103", port = 8080}

# 7. 表
[server]
address = "192.168.0.103"
port = 8080

# 9. 表数组
[[users]]
  name = "user1"
  email = "user1@example.com"

[[users]]
  name = "user2"
  email = "user2@example.com"
